#!/usr/bin/env node
/**
 * brand/tokens.json -> app/tokens.css
 *
 * The generated file is committed so a build never depends on script ordering.
 * scripts/build-tokens.mjs --check fails if the committed file has drifted,
 * which is what stops someone editing tokens.css by hand.
 */
import { readFileSync, writeFileSync } from "node:fs"

const tokens = JSON.parse(readFileSync("brand/tokens.json", "utf8"))

const lines = [
  "/* GENERATED by scripts/build-tokens.mjs from brand/tokens.json. Do not edit. */",
  "@theme {",
  ...Object.entries(tokens.colors).map(([k, v]) => `  --color-${k}: ${v};`),
  ...Object.entries(tokens.on).map(([k, v]) => `  --color-on-${k}: ${v};`),
  `  --font-display: ${tokens.type.display}, ${tokens.type.displayFallback};`,
  `  --font-body: ${tokens.type.body}, ${tokens.type.bodyFallback};`,
  "}",
  "",
  ":root {",
  ...Object.entries(tokens.map).map(([k, v]) => `  --map-${k.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase())}: ${v};`),
  "}",
  "",
]

const css = lines.join("\n")
const target = "app/tokens.css"

if (process.argv.includes("--check")) {
  const current = readFileSync(target, "utf8")
  if (current !== css) {
    console.error(`${target} is out of date. Run: npm run tokens`)
    process.exit(1)
  }
  console.log(`${target} is up to date.`)
} else {
  writeFileSync(target, css)
  console.log(`Wrote ${target}`)
}
